### ISSUE TITLE
Can’t handle diferent file names.

### ISSUE THREAD

**Issue by navid-zamani** [projg2/eclean-kernel#24]
I stopped calling my kernel files “vmlinuz” a long time ago, and eclean-kernel just removed ALL my kernels! If the config files hadn’t been saved somewhere else too, they’d be gone and I would have had to re-install from backups before rebooting, or been left with a broken system. :/

My layout is as follows: In /boot, there are symlinks
.config -> /boot/.config-$currentVersion
.config.stable -> /boot/.config-$lastVersion
. -> /boot/-$currentVersion
..stable -> /boot/-$lastVersion

**Comment by thesamesam** [comment]
You seem to have filed the same bug as https://github.com/mgorny/eclean-kernel/issues/25 (although there's more text in there).

**Comment by ajakk** [comment]
Not sure which close status is best to indicate 'duplicate', but the label is clear.

**Comment by jstrieter** [comment]
The Gentoo distribution kernel package sys-kernel/gentoo-kernel has started calling their kernel "kernel-*" instead of vmlinuz as of 6.6.* so either this issue should be taken seriously or the eclean-kernel package deprecated and it's use discouraged on the [Kernel/Removal](https://wiki.gentoo.org/wiki/Kernel/Removal) page. Or at least a warning should be added.

Yes --pretend can and should be used but can we please make it handle other kernel file names?
